### ISSUE TITLE
Zielgruppe des Schemas

### ISSUE THREAD

**Issue by hemmefelix** [gbv/articleformat#10]
Könntet ihr bitte kurz erläutern, welche Zielgruppe das "JSON-Format zur Lieferung von bibliographischen Metadaten zu Zeitschriftenartikeln an die Verbundzentrale des GBV (VZG)" anspricht? In #8 wurde erwähnt, dass jeder mit Kenntnissen von Pica+ gleich Pica+ Format liefern soll. Geht es darum, dass Inhaltsanbieter die Metadaten im articleformat direkt an euch abliefern? Wir dachten bisher, dass folgender Workflow sinnvoll wäre: Inhaltsanbieter liefert Daten an Bibliothek, z.B. wegen Abschluss eines konsortialen Lizenzvertrags, Bibliothek konvertiert Verlagsdaten in das articleformat und stellt es der VZG zum schnellen Import bereit. Die Daten müssen aber auch ins CBS 1.1 gespielt werden, damit sie dort nachbearbeitet (z.B. normiert) werden können.

**Comment by tillk** [comment]
Zielgruppe sind Bibliotheken, die Artikeldaten haben (woher auch immer), die an die VZG  geliefert werden sollen.
Unser Ziel bei Anwendung des Formats ist es, möglichst viele Schritte eines solchen Prozesses im Vergleich zum bisherigen Ablauf automatisieren, vereinfachen und beschleunigen zu können.
Deswegen wollen wir sowohl die eingesetzte "Technologie" vereinfachen. als auch die Anforderungen ans (insbesondere bibliothekarische) Know-How für solche Lieferungen senken.
Als "Technologie" haben wir JSON plus JSON-Schema gewählt, weil es sich mit praktisch allen verbreiteten Programmierumgebungen verarbeiten lässt und Wissen dazu weit verbreitet ist. JSON-Schema erlaubt außerdem die Spezifikation des Formats, teilautomatische Generierung von Programmcode und insbesondere die einfache Validierung von Daten.
Die Anforderungen ans Know-How  sollen dadurch gesenkt werden, dass das Format möglichst wenig "inhaltlichen Spielraum" lässt und Komplexitäten und Ausnahmebehandlungen, wie sie in Bibliotheksdaten üblich sind, versucht zu vermeiden.
Auch Menschen, die Pica+ kennen, können gerne dieses JSON-Format benutzen. Es erhöht insbesondere die Chance auf eine Beschleunigung und stärkere Automatisierung der Liefer- und Einspielungsprozesse.
Es mag dennoch Fälle geben, in denen Pica+ weiterhin das geeignetere Format ist (insbesondere für alles außer Artikeldaten).
Üblicherweise werden Artikeldatenlieferungen nicht in die Katalogisierungsdatenbank (1.1) übernommen, sondern die Daten landen (ausschließlich) in eigenen Datenbanken im CBS. Es kann Anwendungsfälle geben, in denen eine Übernahme in 1.1 sinnvoll ist. Es kann in solchen Fällen sein, dass die Übertragung von komplexeren Datenstrukturen notwendig ist, die auch bei Nutzung von additional_data in diesem "einfach JSON-Format" nicht sinnvoll zu transportieren sind (spätestens dann, wenn das Objekt in additional_data größer wird als der Rest). In diesen Fällen kann die Lieferung in Pica+ oder gar eine Konvertierung in der Verbundzentrale der bessere Weg sein.
