### ISSUE TITLE
Kurzname

### ISSUE THREAD

**Issue by nichtich** [gbv/articleformat#11]
Ich würde das Format gerne unter https://format.gbv.de/ aufnehmen. Kurzname "vzg-article"?

**Comment by tillk** [comment]
Hmmm, guen Namen oder Kurznamen haben wir nicht. Wem fällt was ein? Vielleicht irgendwas mit "light"/"simple"/...?
Und es ist noch nicht fertig. Ok, Formate sind nie fertig, aber bisher noch nichtmal praxiserprobt.

**Comment by nichtich** [comment]
Ich hab's jetzt unter <http://format.gbv.de/vzg-article> aufgenommen.
