### ISSUE TITLE
title

### ISSUE THREAD

**Issue by tillk** [gbv/articleformat#8]
Bei Artikeln sind auch Untertitel, Zählungen (bei mehrteilig erscheinenden Aufsätzen) und übersetzte Titel (bei Aufsätzen, die in mehreren Sprachen erscheinen) möglich. Damit könnte title zum Object werden (mit Properties maintitle, subtitle und alttitle[]) oder man bräuchte weitere Felder auf oberster Hierarchieebene.

Falls die Ausgangsdaten eine Unterteilung in Haupttitel und Untertitel besitzen, sollte es möglich sein, das im Lieferformat zu übernehmen. Dafür wäre es wie Herr Keßler vorschlagen hat, wohl nötig das Element title zum Objekt zu machen und weitere properties wie subtitle bereitzustellen. Zählungen oder Paralleltitel sind bei unserem Metadatenmaterial der Verlage bisher eher nicht der Fall, es spräche aus unserer Sicht aber auch nichts dagegen dafür properties anzulegen.

**Comment by tillk** [comment]
Titelangaben sind ja ein komplexes Metier beim Katalogisieren. Und dieses Format soll ja einfach anzuwenden sein. Wir halten es deswegen nicht für sinnvoll, weitere Felder vorzugeben, in denen ggf. Teile und Zusätze eines Titels untergebracht werden könnten. Sonst müsste man letztendlich die Komplexität von Katalogisierungsregeln in dem Schema abbilden.
Um das zu verdeutlichen: Nehmen wir an, wir würden lediglich ein zusätzliches Feld "subtitle" vorsehen: Nun enthalten Daten eines Lieferanten Titel in mehreren Sprachen, für die aber im Schema kein eigenes Feld vorgesehen wäre. Wir halten die Wahrscheinlichkeit für hoch, dass die mehrsprachigen Titel dann mangels anderer Möglichkeit in "subtitlte" landen könnten, was eine sinnvollen Automatisierung von Prozessen erschwert.
Wir hätten deswegen gerne, dass in dem String-Feld title genau ein "sinnvoller" Titel für den Artikel, den der Datensatz beschreibt, geliefert wird. "Sinnvoll" bezieht sich hier auf die Nutzung in allgemeinen Endbenutzerumgebungen. Dieser "sinnvolle" Titel kann ggf. aus mehreren Teilen des Titels in der Datenquelle konstruiert sein, z.B. Haupttitel: "Research on Phosphatases of Belladona Leaves and Their Purification" plus Zusatz: "Part 1" -> 'title': 'Research on Phosphatases of Belladona Leaves and Their Purification, Part 1'
Falls für eine Datensammlung eine komplexere Datenstruktur zur Abbildung von Titeln notwendig ist, so kann diese im Feld [additional_data](https://github.com/gbv/articleformat/blob/28118beb5d725eb309f48347d4619b8f4ab12573/article_schema.json#L373) modelliert, spezifiziert und untergebracht werden. Damit ist eine Modellierung von Titeldaten in Abhängigkeit von konkreten Projekten zielgenau möglich, was uns sinnvoller erscheint als eine Vorgabe spezifischerer Felder durch das Schema, die dann aber ggf. doch nicht ausreichen, um die projektbezogene Komplexität abzubilden.

**Comment by hemmefelix** [comment]
Hi @tillk , sorry dass ich dein geschlossenes Issue kommentiere. Ich verstehe die obigen Überlegungen und Gründe sehr gut. Ist es von deiner Seite aus denkbar, beim Mapping JSON => Pica+ den Wert aus title anhand von eindeutigen Delimitern auf 021A $a und $d aufzuteilen? 
Wenn ich es richtig verstehe, dient das einfache JSON-Artikelformat erst einmal dazu, Daten in K10plus-Zentral zu importieren. Uns ist es aber wichtiger, die Daten im CBS zu haben, da wir euren Index nicht nutzen. Deshalb haben wir das immer im Hinterkopf.

**Comment by tillk** [comment]
Nein, keine Trennzeichen innerhalb von Feldern! Von dem ganzen Mist wollen wir doch weg. Und auch dazu müsste der Import angepasst werden.
Die Idee des Formats ist die Lieferung von Artikeldaten in einem einfach - insbesondere ohne tiefergehende bibliothekarische Kenntnisse - anwendbaren Format. Wer 021A $a und $d kennt, kann auch gleich Pica+ liefern.
Wie gesagt: Nach Absprache und Spezifikation ist es möglich, komplexere Datenstrukturen in additional_data unterzubringen. Auch dazu muss der Import angepasst werden, die Daten sind dann aber wenigstens klar strukturiert. additional_data ist erstmal nicht weiter spezifiziert, vielleicht wird sich das ändern, insbesondere um daraus vielleicht direkt Code für die Konvertierung nach PIca+ generieren zu können. Aber soweit sind wir noch nicht, erstmal Erfahrung sammeln (siehe dazu auch #9 ).
